pub mod canasta;
pub mod cards;
pub mod euchre24;
pub mod euchre32;
pub mod french;
pub mod pinochle;
pub mod razz;
pub mod short;
pub mod skat;
pub mod spades;
pub mod standard52;
pub mod tarot;
mod tiny;
