FROM mcr.microsoft.com/devcontainers/rust:latest

# install a few tools for more convenient developing
#RUN  apt-get update; \
#    apt-get -y install --fix-missing \
#    git python3 cmake g++ python-is-python3

# [Optional] Uncomment this section to install additional packages.
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends python-is-python3

# Add ./bin to PATH
ENV PATH="./bin:${PATH}"
