FROM mcr.microsoft.com/devcontainers/rust:latest

# [Optional] Uncomment this section to install additional packages.
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends python-is-python3

# Add ./bin to PATH
ENV PATH="./bin:${PATH}"
